accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name="accounts"
urlpatterns = [
   
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('register/', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    ]
   

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('accounts/',include('accounts.urls')),
    path('ideas/',include('ideas.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name="ideas"
urlpatterns = [
    path('create/', views.create, name="create"),
     path('delete/<int:idea_id>', views.delete, name="delete"),
      path('edit/<int:idea_id>', views.edit, name="edit"),
       path('view/<int:idea_id>', views.view, name="view"),
        path('vote/<int:idea_id>', views.vote, name="vote"),
        path('comment/', views.comment, name="comment"),
        path('list/', views.IdeaList.as_view()),
        path('api/', views.IdeaApiList.as_view()),
        path('api/<int:pk>', views.IdeaApiDetail.as_view()),

    ]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='London')

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=100, default='')
    website = models.URLField(default='')
    phone = models.IntegerField(default=0)
    image = models.ImageField(upload_to="images/")

    london = UserProfileManager()

    def __str__(self):
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from accounts.models import UserProfile


class EditProfileForm(UserChangeForm):
    template_name='/something/else'
    image = forms.ImageField(label = 'Image', required =False)
    image.widget.attrs.update({'class':'form-control'})
    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'password',
        )
        

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from ideas.models import Idea
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.forms import (
    EditProfileForm
)

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        if request.POST['password'] == request.POST['password-confirm']:
            try:
                user = User.objects.get(username=request.POST['username'])
                messages.add_message(request, messages.ERROR, 'User already exists! please use another name')
                return redirect('accounts:register')
                #return redirect('accounts:register')
            except User.DoesNotExist:
                user = User.objects.create_user(username = request.POST['username'],password = request.POST['password'])
                messages.add_message(request, messages.SUCCESS, 'Successful')
                return redirect('accounts:login')
        else:
            messages.add_message(request, messages.ERROR, 'Passwords DO NOT MAtch')
            return redirect('accounts:register')
    else:
        return render(request, 'accounts/register.html', {'page_title':'Register'})

def login(request):
	if request.method == 'POST':
		user = auth.authenticate(request, username = request.POST['username'],password = request.POST['password'])
		if user is not None:
			auth.login(request,user)
			messages.add_message(request, messages.SUCCESS, 'Successful')
			return redirect('welcome:home')

		else:
			messages.add_message(request, messages.ERROR, 'username and Passwords DO NOT MAtch')
			return redirect('accounts:login')
	else:
 		return render(request, 'accounts/login.html', {'page_title':'Login'})

def logout(request):
	auth.logout(request)
	messages.add_message(request, messages.SUCCESS, 'Successfully logged_out')
	return redirect('accounts:login')

@login_required(login_url="accounts:login")
def dashboard(request):
	user = request.user
	data = Idea.objects.filter(user=user)
	print(data)
	return render(request, 'accounts/dashboard.html', {'page_title':'Dashboard', 'ideas':data})



def view_profile(request, pk=None):
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
        data = Idea.objects.filter(user=user)
    args = {'user': user, 'ideas':data}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
        else:
            return redirect(reverse('accounts:change_password'))
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args)

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block content %}

<main class="container pt-5">
		
		
		<section class="col-12">

		<h1>Dashboard</h1>

		<table class="table table-hover">
			<tr>
				<th>SN</th>
				<th></th>
				<th>Title</th>
				<th>Created</th>
				<th>view</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>

		{% for idea in ideas %}
		<tr>
			<td>{{forloop.counter}}</td>
			<td><img src="/media/{{idea.image}}" class="img img-fluid" style="height:50px"></td>
			<td>{{idea.title}}</td>
			<td>{{idea.created}}</td>
			<td> <a class="btn btn-secondary" href="{% url 'ideas:view' idea.id %}">View</a></td>
			<td> <a class="btn btn-primary" href="{% url 'ideas:edit' idea.id %}">Edit</a></td>
			<td> <a class="btn btn-danger" href="{% url 'ideas:delete' idea.id %}">Delete</a></td>
		</tr>

		{% endfor %}
	</table>
			
		</section>
		
		
	</main>
	
{% endblock %}

templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
    <br>
</div>

{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<main class="container pt-5">
		
		
		<section class=" col-md-6 col-12 offset-md-3 ">

		<h1>Sign In</h1>
			<form id="loginForm" method="POST" action="{% url 'accounts:login' %}">
				{% csrf_token %}
				<fieldset class="form-group">
					<label>Username</label>
					<input type="text" class="form-control m-2" name = "username">	
				</fieldset>
				<fieldset class="form-group">
					<label>Password</label>
					<input type="password" class="form-control m-2" name = "password">	
				</fieldset>
				
				<button class="btn btn-primary">Submit</button>
			</form>
			<br>
			<fieldset class="form-group">
					<a href="{% url 'accounts:register' %}">Register here!</a>
				</fieldset>
		</section>
		
		<script>
			$(documnent).ready(function(){
			$('#loginForm'),validate({
				rules:{
					username:'required',
					password:'required'
				}
			});
		})
		</script>
	</main>


{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h1>Profile</h1>
    <p>Username: {{ user }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    
    {% for user in users %}
    <img src="{{ user.image }}" width="240">
    {% endfor %}
</div>
<section class="col-12">


        <table class="table table-hover">
            <tr>
                <th>SN</th>
                <th></th>
                <th>Title</th>
                <th>Created</th>
                <th>view</th>
            </tr>

        {% for idea in ideas %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td><img src="/media/{{idea.image}}" class="img img-fluid" style="height:50px"></td>
            <td>{{idea.title}}</td>
            <td>{{idea.created}}</td>
            <td> <a class="btn btn-secondary" href="{% url 'ideas:view' idea.id %}">View</a></td>
            
        </tr>

        {% endfor %}
    </table>
            
        </section>
{% endblock %}

templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}

<main class="container pt-5" style="">
		
		

		<section class=" col-md-6 col-12 offset-md-3" style="">
			
			<h1>Sign Up</h1>
			<form id="registerForm" method="POST" action="{% url 'accounts:register' %}">
				{% csrf_token %}
				
				<fieldset class="form-group">
					<label>Username</label>
					<input type="text" class="form-control m-2" name = "username">	
				</fieldset>
				<fieldset class="form-group">
					<label>Password</label>
					<input type="password" class="form-control m-2" name = "password">	
				</fieldset>
				<fieldset class="form-group">
					<label>Confirm-Password</label>
					<input type="password" class="form-control m-2" name = "password-confirm">	
				</fieldset>
				<button class="btn btn-primary">Register</button>
			</form>
			
		</section>
		
		
	</main>


{% endblock %}