ideas/urls.py
from django.urls import path
from . import views

app_name="ideas"
urlpatterns = [
    path('create/', views.create, name="create"),
     path('delete/<int:idea_id>', views.delete, name="delete"),
      path('edit/<int:idea_id>', views.edit, name="edit"),
       path('view/<int:idea_id>', views.view, name="view"),
        path('vote/<int:idea_id>', views.vote, name="vote"),
        path('comment/', views.comment, name="comment"),
        path('list/', views.IdeaList.as_view()),
        path('api/', views.IdeaApiList.as_view()),
        path('api/<int:pk>', views.IdeaApiDetail.as_view()),

    ]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('accounts/',include('accounts.urls')),
    path('ideas/',include('ideas.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name="ideas"
urlpatterns = [
    path('create/', views.create, name="create"),
     path('delete/<int:idea_id>', views.delete, name="delete"),
      path('edit/<int:idea_id>', views.edit, name="edit"),
       path('view/<int:idea_id>', views.view, name="view"),
        path('vote/<int:idea_id>', views.vote, name="vote"),
        path('comment/', views.comment, name="comment"),
        path('list/', views.IdeaList.as_view()),
        path('api/', views.IdeaApiList.as_view()),
        path('api/<int:pk>', views.IdeaApiDetail.as_view()),

    ]

ideas/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class Idea(models.Model):
	title = models.CharField(max_length=50)
	image = models.ImageField(upload_to="images/")
	description = models.TextField()
	created = models.DateTimeField(default=timezone.now)
	user = models.ForeignKey(User, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class Comment(models.Model):
	comment = models.TextField()
	created = models.DateTimeField(default=timezone.now)
	# updated = models.DateTimeField(default=timezone.now,on_update=timezone.now)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

	def __str__(self):
		return self.comment

class Vote(models.Model):
	VOTE_CHOICES = (
		('U',"Upvote"),
		('D',"Downvote")
		)
	vote = models.CharField(
		max_length = 1,
		choices = VOTE_CHOICES
		)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	idea = models.ForeignKey(Idea, on_delete=models.CASCADE)

	def __str__(self):
		return self.vote

ideas/forms.py
from django import forms
from .models import Comment

class IdeaForm(forms.Form):
	title = forms.CharField(label = 'Title')
	image = forms.ImageField(label = 'Image', required =False)
	description = forms.CharField(label = 'Description',widget = forms.Textarea)
	
	title.widget.attrs.update({'class':'form-control'})
	image.widget.attrs.update({'class':'form-control'})
	description.widget.attrs.update({'class':'form-control'})

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['comment', 'user', 'idea']
		widgets = {
			'comment' : forms.Textarea(attrs={
				'class': 'form-control',
				'rows': 2
			}),
			'user' : forms.HiddenInput(),
			'idea' : forms.HiddenInput(),
			}

ideas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from . forms import IdeaForm
from . models import Idea, Comment, Vote
from django.http import HttpResponse, JsonResponse
from django.contrib import auth, messages
from django.utils.datastructures import MultiValueDictKeyError
from .forms import IdeaForm, CommentForm
from django.views.generic import ListView
from django.core.mail import send_mail


from django.template.loader import render_to_string
from rest_framework import generics
from .serializers import IdeaSerializer

# Create your views here.

@login_required(login_url="accounts:login")
def create(request):
	if request.method == 'POST':
		form = IdeaForm(request.POST or None, request.FILES or None)
		if form.is_valid:
			idea = Idea()
			idea.user = request.user
			# idea.title = form.cleaned_data['title']
			idea.title = request.POST['title']
			idea.description = request.POST['description']
			try:
				idea.image = request.FILES['image']
			except MultiValueDictKeyError:
				pass
			idea.save()
			messages.add_message(request,messages.SUCCESS,"Successfully created!")
			return redirect('accounts:dashboard')

		else:
			return render(request, 'ideas/create.html', {'page_title':'Add Your Idea','form':form})

	else:
		form = IdeaForm()
		return render(request, 'ideas/create.html', {'page_title':'Add Your Idea','form':form})
	# form = IdeaForm(request.POST or None)

	# if request.method == 'POST':
		
	# 	if form.is_valid:
	# 		return HttpResponse('Valid')

	# else:
	# 	return render(request, 'ideas/create.html', {'page_title':'Add Your Idea','form':form})

@login_required(login_url="accounts:login")
def delete(request, idea_id):
	user = request.user
	try:
		idea = Idea.objects.get(pk=idea_id)
	except Idea.DoesNotExist:
		messages.add_message(request,messages.ERROR,"Invalid request!")
		return redirect('accounts:dashboard')
	if user == idea.user:
		idea.delete()
		messages.add_message(request,messages.SUCCESS,"Successfully Deleted!")
		return redirect('accounts:dashboard')

	messages.add_message(request,messages.ERROR,"Invalid request!")
	return redirect('accounts:dashboard')
	
@login_required(login_url="accounts:login")
def edit(request, idea_id):
	user = request.user
	try:
		idea = Idea.objects.get(pk=idea_id)
	except Idea.DoesNotExist:
		messages.add_message(request,messages.ERROR,"Invalid request!")
		return redirect('accounts:dashboard')

	form = IdeaForm(request.POST or None, request.FILES or None)
	if request.method == 'POST':
		if form.is_valid():
			idea.user = request.user
			idea.title = request.POST['title']
			idea.description = request.POST['description']
			try:
				idea.image = request.FILES['image']
			except MultiValueDictKeyError:
				pass
			idea.save()
			messages.add_message(request,messages.SUCCESS,"Successfully Edited {}!".format(request.POST['title']))
			return redirect('accounts:dashboard')

		else:
			return render(request, 'ideas/create.html', {'page_title':'Edit your idea','form':form, 'id':idea.id})


	else:
		form = IdeaForm(initial={'title':idea.title , 'description':idea.description})
		return render(request, 'ideas/create.html', {'page_title':'Edit your idea','form':form, 'id':idea.id})

def view(request, idea_id):
	idea = get_object_or_404(Idea, pk = idea_id)
	comment_form = CommentForm(initial={'user':request.user.id, 'idea':idea_id})
	comments = Comment.objects.filter(idea=idea_id)
	vote = Vote.objects.filter(user=request.user,idea=idea)
	data = {
		'page_title':idea.title,
		'idea':idea,
		'comment_form':comment_form,
		'comments':comments,
		'vote':'No'
	}
	if vote.count()> 0:
		data['vote'] = vote[0].vote

	html_email = render_to_string('ideas/view.html',data)

	send_mail('Test','Test Message','TestFrom',['abc@gmail.com'],'ideas/view.html',html_message = html_email)
	return render(request, 'ideas/view.html', {
												'page_title':idea.title,
												'idea':idea, 
												'comment_form':comment_form,
												'comments':comments,
												})


def comment(request):

	if str(request.user) == 'AnonymousUser':
		messages.add_message(request,messages.ERROR,"Invalid Request!")
		return redirect('accounts:login')


	if str(request.user.id) == request.POST['user']:
		form = CommentForm(request.POST)
		if form.is_valid():
			form.save()
			messages.add_message(request,messages.SUCCESS,"Successfully Commented!")
			return redirect('ideas:view',idea_id = request.POST['idea'])
	messages.add_message(request,messages.ERROR,"Invalid Request!")
	return redirect('accounts:dashboard')


def vote(request, idea_id):
	user = request.user
	if user.id == None:
		return JsonResponse({'class': 'error', 'message': 'You should login to vote'})
	try:
		idea = Idea.objects.get(pk=idea_id)
	except Idea.DoesNotExist:
		return JsonResponse({'class': 'error', 'message': 'Invalid request'})

	vote = Vote.objects.filter(user=user, idea=idea)
	print(vote)


	if vote.count() == 0:
		voteObj = Vote(vote = request.POST['vote'], user=user, idea=idea)
		voteObj.save()
		if request.POST['vote'] == 'U':
			return JsonResponse({'class': 'success', 'message': 'Successfully Liked'})
		return JsonResponse({'class': 'success', 'message': 'Successfully DisLiked'})
		
	vote.delete()
	return JsonResponse('VoteDeleted',safe=False)



class IdeaList(ListView):

	model = Idea
	template_name = 'accounts/dashboard.html'
	context_object_name = 'ideas'


class IdeaApiList(generics.ListAPIView):
	queryset = Idea.objects.all()
	serializer_class = IdeaSerializer


class IdeaApiDetail(generics.RetrieveUpdateDestroyAPIView):
	queryset = Idea.objects.all()
	serializer_class = IdeaSerializer

templates/ideas/create.html
{% extends 'base.html' %}

{% block content %}

<main class="container pt-5">
		
		
		<section class=" col-md-6 col-12 offset-md-3 ">
			{% if page_title == 'Add Your Idea' %}

		<h1>Add Your Idea</h1>
			<form id="CreateIdeaForm" method="POST" action="{% url 'ideas:create' %}" enctype="multipart/form-data">
			{% else %}
			<h1>Edit Your Idea</h1>
			<form id="CreateIdeaForm" method="POST" action="{% url 'ideas:edit' id %}" enctype="multipart/form-data">
			{% endif %}
				{% csrf_token %}
			
			
			{# 	{{ form.as_p }} #}
				{# form.as_table,form.as_ul  #}
				<fieldset class="form-group">
					{% if form.title.error %}
					<p> {{ form.title.error }}</p>
					{% endif %}
					<label>{{ form.title.label }}</label>
					{{ form.title }}
				</fieldset>
				 <fieldset class="form-group">
					<label>{{ form.image.label }}</label>
					{{ form.image }}
				</fieldset>
				 <fieldset class="form-group">
					<label>{{ form.description.label }}</label>
					{{ form.description }}
				</fieldset> 
				 				<button class="btn btn-primary">Submit</button>
			<!-- {% for field in form %}
			<fieldset class="form-group">
				 	<label>{{ field.label }}</label>
				 	{{ field }}
				 </fieldset>
				 {% endfor %}
				 <button class="btn btn-primary">Submit</button> -->
			</form>
			</form>
		</section>
		
		
	</main>
	<script>
		
	</script>


{% endblock %}

templates/ideas/view.html
{% extends 'base.html' %}

{% block content %}

<main class="container pt-5">


	<section class="col-12">
		<div class="row">
			
			
			<header class="mr-auto">
				<h1>{{ idea.title }}</h1>
				<small>Published: {{ idea.created }} | User: {{ idea.user }}</small>
			</header>
			<div class="ml-auto">
				<span data-value="U" data-action="vote"><i class="fa fa-thumbs-up fa-2x" style="color: {% if vote == 'U' %}blue{% else %}grey{% endif %}">
				</i></span>
				<span data-value="D" data-action="vote"><i class="fa fa-thumbs-down fa-2x" style="color: {% if vote == 'D' %}red{% else %}grey{% endif %}"></i></span>
			</div>
		</div>	
		
		<figure>
			<img src="/media/{{ idea.image }}" class="img img-fluid">

		</figure>
		<h3>Description</h3>
		<article class="pt-3"> {{ idea.description }}</article>

	</section>
	<div>
		

		<header>
			<br>
			<h3>Comments</h3>
			
		</header>
		{% for comment in comments %}
		<section class="card card-body" style="background-color:aqua">
			<div>

				
				<small>{{ comment.created }} | User: {{ comment.user }}</small>
			</div>
			<article>{{comment.comment}}</article>

		</section>
		{% endfor %}

	</div>

	<form action="{% url 'ideas:comment' %}" method="POST" class="pt-5">
		{% csrf_token %}
		<label>Add Your Comment</label>
		<fieldset class="form-group" >
			{{ comment_form.comment }}
		</fieldset>
		{{ comment_form.user }} {{ comment_form.idea }}
		<input type="submit" value="comment" class="btn btn-primary">
	</form>
</main>
<script>

	function getCookie(name) {
		var cookieValue = null;
		if (document.cookie && document.cookie !== '') {
			var cookies = document.cookie.split(';');
			for (var i = 0; i < cookies.length; i++) {
				var cookie = jQuery.trim(cookies[i]);
    // Does this cookie string begin with the name we want?
    if (cookie.substring(0, name.length + 1) === (name + '=')) {
    	cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
    	break;
    }
}
}
return cookieValue;
}
$(document).ready(function() {

            $('[data-action="vote"]').on('click', function() {
                var vote = $(this).attr('data-value')
                var $this = $(this)

                $.ajax({
                    url: "{% url 'ideas:vote' idea.id %}",
                    headers: {
                        "X-CSRFToken": getCookie("csrftoken")
                    },
                    data: {
                        'vote': vote
                    },
                    dataType: 'json',
                    method: 'POST',
                    success: function(res) {
                        let clas = res.class
                        let message = res.message
                        if (clas == 'error') {
                            toastr.error(message)
                        } else {
                            toastr.success(message)
                        }
                        if (res.status && res.status == 'Removed') {

                            $this.children('i').css('color', 'grey')
                            $this.children('i').animate({fontSize: '3em'})
                            $this.children('i').animate({fontSize: '2em'})

                        } else if (vote == 'D') {
                            $this.children('i').css('color', 'tomato')
                            $this.children('i').animate({fontSize: '3em'})
                            $this.children('i').animate({fontSize: '2em'})
                            
                        } else {
                            $this.children('i').css('color', 'blue')
                            $this.children('i').animate({fontSize: '3em'})
                            $this.children('i').animate({fontSize: '2em'})
                        }
                    },
                    error: function(res) {
                        toastr.error("An Error Occured")
                    }
                })
            })

        });

</script>

{% endblock %}