accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name="accounts"
urlpatterns = [
   
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('register/', views.register, name='register'),
    url(r'^profile/$', views.view_profile, name='view_profile'),
    url(r'^profile/(?P<pk>\d+)/$', views.view_profile, name='view_profile_with_pk'),
    url(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),

    ]
   

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('welcome.urls')),
    path('accounts/',include('accounts.urls')),
    path('ideas/',include('ideas.urls')),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views

app_name="ideas"
urlpatterns = [
    path('create/', views.create, name="create"),
     path('delete/<int:idea_id>', views.delete, name="delete"),
      path('edit/<int:idea_id>', views.edit, name="edit"),
       path('view/<int:idea_id>', views.view, name="view"),
        path('vote/<int:idea_id>', views.vote, name="vote"),
        path('comment/', views.comment, name="comment"),
        path('list/', views.IdeaList.as_view()),
        path('api/', views.IdeaApiList.as_view()),
        path('api/<int:pk>', views.IdeaApiDetail.as_view()),

    ]

welcome/urls.py
from django.urls import path
from .import views

app_name="welcome"
urlpatterns = [
    path('', views.home, name="home"),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title> {{page_title}}</title>
	<link rel="stylesheet" href = "{% static 'css/bootstrap.css' %}">
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <link rel="stylesheet" href = "{% static 'css/toastr.css' %}">

  <script async src="{% static 'js/jquery.js' %}"></script>
	
</head>
<body>
	<header>
	<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      
    
  <a class="navbar-brand" href="{% url 'welcome:home' %}">Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'accounts:dashboard' %}">Dashboard <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item">
         <a class="nav-link" href="{% url 'ideas:create' %}">Post an Idea <span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'accounts:view_profile' %}">Profile<span class="sr-only">(current)</span></a>
      </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'accounts:edit_profile' %}">Edit Profile <span class="sr-only">(current)</span></a>
      </li>
     
       {% endif %}
       <li class="nav-item">
         <a class="nav-link" href="#">Other User <span class="sr-only">(current)</span></a>
      </li>
  </ul>
  <ul class="navbar-nav ml-auto">
    {% if not user.is_authenticated %}
      <li class="nav-item {% if page_title == 'Login' %} active{% endif %}">
        <a class="nav-link" href="{% url 'accounts:login' %}"><i class="fa fa-sign-in-alt">Login</i></a>
      </li>
      <li class="nav-item {% if page_title == 'Register' %} active{% endif %}"">
        <a class="nav-link " href="{% url 'accounts:register' %}"><i class="fa fa-user">Register</i></a>
      </li>
      {% else %}
         <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-in-alt">Logout</i></a>
      </li>
      {% endif %}
       
    </ul>

  </div>
  </div>
</nav>
	</header>
	{% block content %} {% endblock %}
  <script src="{% static 'js/toastr.min.js' %}"></script>
  <script defer src="{% static 'js/popper.js' %}"></script>
  <script defer src="{% static 'js/bootstrap.js' %}"></script>
   <script defer src="{% static 'js/form_validation.js' %}"></script>
  

{% if messages %} {% for message in messages %}
<script>
  toastr.{{message.tags}}("{{message}}")
  
toastr.options = {
  "closeButton": true,
  "debug": true,
  "newestOnTop": true,
  "progressBar": true,
  "positionClass": "toast-bottom-right",
  "preventDuplicates": true,
  "showDuration": "300",
  "hideDuration": "1000",
  "timeOut": 0,
  "extendedTimeOut": 0,
  "showEasing": "swing",
  "hideEasing": "linear",
  "showMethod": "fadeIn",
  "hideMethod": "fadeOut",
  "tapToDismiss": false
}
</script>
{% endfor %} {% endif %}
</body>
</html>